[build]
  publish = "."
  command = "echo 'No build required for static HTML'"

[[redirects]]
  from = "/"
  to = "/editable_email_template.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"